// In react-popup-src/vite.config.ts
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
// import path from 'path'; // Keep if you plan to use path resolution later, otherwise remove

// https://vitejs.dev/config/
export default defineConfig({
  base: './',
  plugins: [react()],
  build: {
    // Output to a 'dist' folder INSIDE react-popup-src
    // This is the standard and recommended way.
    outDir: 'dist',

    // Set to true (or remove line) to clean the 'dist' folder before each build.
    // Set to false ONLY if 'dist' might contain files not generated by Vite
    // that you need to preserve. Usually 'true' is safer.
    emptyOutDir: true, // Changed to true, assuming 'dist' only contains build output

    rollupOptions: {
      output: {
        // Configure output filenames
        entryFileNames: `assets/popup.js`, // Put JS in an assets subfolder
        assetFileNames: `assets/[name].[ext]`, // Put CSS, images etc. in assets
        chunkFileNames: `assets/[name].js`, // Put code-split chunks in assets
      }
    }
  },
  // Optional: If you need to resolve paths relative to the project root
  // resolve: {
  //   alias: {
  //     '@': path.resolve(__dirname, './src'), // Example alias
  //   },
  // },
})